# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tempate/sublearn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.hold_word_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hold_word_lineEdit.setText("")
        self.hold_word_lineEdit.setObjectName("hold_word_lineEdit")
        self.gridLayout.addWidget(self.hold_word_lineEdit, 3, 0, 1, 3)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setObjectName("next_button")
        self.gridLayout.addWidget(self.next_button, 1, 2, 1, 1)
        self.translateArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.translateArea.setPlainText("")
        self.translateArea.setObjectName("translateArea")
        self.gridLayout.addWidget(self.translateArea, 4, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWord = QtWidgets.QListWidget(self.centralwidget)
        self.listWord.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWord.setObjectName("listWord")
        self.horizontalLayout.addWidget(self.listWord)
        self.listSentences = QtWidgets.QListWidget(self.centralwidget)
        self.listSentences.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listSentences.setObjectName("listSentences")
        self.horizontalLayout.addWidget(self.listSentences)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setObjectName("previous_button")
        self.gridLayout.addWidget(self.previous_button, 1, 1, 1, 1)
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setObjectName("open_button")
        self.gridLayout.addWidget(self.open_button, 1, 0, 1, 1)
        self.tableSub = QtWidgets.QTableWidget(self.centralwidget)
        self.tableSub.setMinimumSize(QtCore.QSize(0, 300))
        self.tableSub.setObjectName("tableSub")
        self.tableSub.setColumnCount(1)
        self.tableSub.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSub.setHorizontalHeaderItem(0, item)
        self.tableSub.horizontalHeader().setDefaultSectionSize(50)
        self.tableSub.horizontalHeader().setMinimumSectionSize(30)
        self.tableSub.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableSub, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        item = self.tableSub.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sentences"))
